try comment on PR

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -120,5 +120,29 @@ jobs:
       - name: Deploy PR Stage
         run: pnpm sst deploy --stage pr-${{ github.event.pull_request.number }}
 
-        
+      - name: Read webApp from output.json
+        run: |
+          if [ -f ".sst/output.json" ]; then
+            webApp=$(jq -r '.webApp' .sst/output.json)
+            echo "webApp=$webApp" >> $GITHUB_ENV
+          else
+            echo "sst output file not found. Exiting."
+            exit 1
+          fi
+
+      - name: Add comment to PR
+        uses: actions/github-script@v7
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          script: |
+            const webApp = process.env.webApp;
+            const prNumber = context.issue.number;
+            const commentBody = `WebApp URL: \`${webApp}\``;
+            await github.rest.issues.createComment({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: prNumber,
+              body: commentBody,
+            });
     
