greping wont work

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -122,21 +122,15 @@ jobs:
         id: sst
         run: pnpm sst deploy --stage pr-${{ github.event.pull_request.number }}
 
-      # - name: Read webApp from output.json
-      #   run: |
-      #     if [ -f ".sst/outputs.json" ]; then
-      #       webApp=$(jq -r '.webApp' .sst/outputs.json)
-      #       echo "webApp=$webApp" >> $GITHUB_ENV
-      #     else
-      #       echo "sst outputs file not found. Exiting."
-      #       exit 1
-      #     fi
-
-      - name: Capture Stage URL from output
+      - name: Read webApp from output.json
         run: |
-          url=$(echo "${{ steps.sst.outputs.stdout }}" | grep -oP '(?<=webApp: ).*')
-          echo "webAppURL=$url" >> $GITHUB_ENV
-
+          if [ -f ".sst/outputs.json" ]; then
+            webApp=$(jq -r '.webApp' .sst/outputs.json)
+            echo "webApp=$webApp" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 1
+          fi
 
       - name: Add comment to PR
         uses: actions/github-script@v7
