i feel good about this one

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -119,17 +119,24 @@ jobs:
         run: pnpm install
 
       - name: Deploy PR Stage
+        id: sst
         run: pnpm sst deploy --stage pr-${{ github.event.pull_request.number }}
 
-      - name: Read webApp from output.json
+      # - name: Read webApp from output.json
+      #   run: |
+      #     if [ -f ".sst/outputs.json" ]; then
+      #       webApp=$(jq -r '.webApp' .sst/outputs.json)
+      #       echo "webApp=$webApp" >> $GITHUB_ENV
+      #     else
+      #       echo "sst outputs file not found. Exiting."
+      #       exit 1
+      #     fi
+
+      - name: Capture Stage URL from output
         run: |
-          if [ -f ".sst/outputs.json" ]; then
-            webApp=$(jq -r '.webApp' .sst/outputs.json)
-            echo "webApp=$webApp" >> $GITHUB_ENV
-          else
-            echo "sst outputs file not found. Exiting."
-            exit 1
-          fi
+          url=$(echo "${{ steps.sst.outputs.stdout }}" | grep -oP '(?<=webApp: ).*')
+          echo "webAppURL=$url" >> $GITHUB_ENV
+
 
       - name: Add comment to PR
         uses: actions/github-script@v7
@@ -139,10 +146,32 @@ jobs:
             const webApp = process.env.webApp;
             const prNumber = context.issue.number;
             const commentBody = `WebApp URL: \`${webApp}\``;
-            await github.rest.issues.createComment({
+
+            const { data: comments } = await github.rest.issues.listComments({
               owner: context.repo.owner,
               repo: context.repo.repo,
               issue_number: prNumber,
-              body: commentBody,
             });
+
+            console.log(comments);
+
+            const existingComment = comments.find(comment => comment.body.startsWith("WebApp URL:"));
+
+            if (existingComment) {
+              // Update the existing comment
+              await github.rest.issues.updateComment({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                comment_id: existingComment.id,
+                body: commentBody,
+              });
+            } else {
+              // Create a new comment if none exists
+              await github.rest.issues.createComment({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                issue_number: prNumber,
+                body: commentBody,
+              });
+            }
     
